# Generated by Django 4.2 on 2025-04-24 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.SmallIntegerField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pre_approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customers_customer',
            },
        ),
    ]
