# Generated by Django 4.2 on 2025-04-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
