# Generated by Django 4.2 on 2025-04-24 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='external_id',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
