# Generated by Django 4.2 on 2025-04-24 22:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=60, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.SmallIntegerField()),
                ('contract_version', models.CharField(blank=True, max_length=30, null=True)),
                ('maximum_payment_date', models.DateTimeField(blank=True, null=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('outstanding', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customers.customers')),
            ],
            options={
                'db_table': 'loans_loan',
            },
        ),
    ]
